inputs:
  branchOrTag:
    description: 'Git branch or tag'
    default: 'No branch or tag provided'
  buildPath:
    description: 'Directory for build'
    default: 'No buildPath provided'
  pubPath:
    description: 'Directory for publish'
    default: 'No pubPath provided'
  site:
    description: 'IIS site name'
    default: 'No site provided'
  envName:
    description: 'Environment'
    default: 'No env provided'
  archivePath:
    description: 'Directory for archiving previous deploy.'
    default: 'No archivePath provided'
  assemblyFilePath:
      description: 'The .DLL containing version info.'
      default: 'No assemblyFilePath provided'
runs:
  using: "composite"
  steps:
    - name: Archive
      run: $v = [Reflection.AssemblyName]::GetAssemblyName('${{ inputs.assemblyFilePath }}').Version; Compress-Archive -Path '${{ inputs.pubPath }}' -CompressionLevel "Fastest" -DestinationPath '${{ inputs.archivePath }}'.$v.Zip -Update
      shell: powershell

    # Local runner service account needs elevated to 'system'.
    - name: Shutdown site
      run: Stop-WebSite '${{ inputs.site }}'
      shell: powershell

    - name: Publish
      run: |
        robocopy '${{ inputs.buildPath }}' '${{ inputs.pubPath }}' /s /mir /xf "Web.config"
        if( $LASTEXITCODE -ge 8 )
        {
            throw ("An error occured while copying. [RoboCopyCode: $($LASTEXITCODE)]")
        }
        else
        {
            $global:LASTEXITCODE = 0;
        }
        exit 0
      shell: powershell

    # Local runner service account needs elevated to 'system'.
    - name: Start site
      run: Start-WebSite '${{ inputs.site }}'
      shell: powershell
